version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=production
    command: node server.js

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
