services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./frontend-react:/app
    command: npm start
